### DISCUSSION TITLE
Admin Credentials to OptScale

### DISCUSSION THREAD

**Discussion by daviftorres** [hystax/optscale#509] [General]
Hello there,
Is there any default credentials after a fresh installation? Or the "admin" account is set during the installation and I missed to configure?
Best regards,

**Comment by daviftorres** [comment]
Update: I think out of the box, if the SMTP is configured, any visitor can sign-up, receive the invitation email and start using.

Am I right?

**Comment by stanfra** [comment]
Hi @daviftorres,
1 - There are no default credentials or "admin" account creation during installation, you need to register in OptScale and use created organization as organization manager.
2 - Yes, you right. Visitor can register, verify email and start using OptScale or register by invitation link in email

**Reply by ghost** [reply]
Much appreciated your reply, @stanfra.

I found out the email is not being sent and the SMTP server has logged this error:

```
Mailer: from=<root@heraldengine-54dbcbcb58-2ndd5>,reject=452 4.5.2 Could not resolve sender domain.
```

Am I doing it right?

```
smtp:
  server: smtp.example.com
  email: finops@example.com
  login: finops
  port: 25
  password: no-password-required
  protocol: SMTP
```
