### DISCUSSION TITLE
Support for mongodb+srv in OptScale

### DISCUSSION THREAD

**Discussion by cupello** [hystax/optscale#600] [Q&A] [answered]
Hello,

I'm trying to configure OptScale to connect to a MongoDB instance using the mongodb+srv connection string format. However, I couldn't find any documentation or examples specifying whether this format is supported.

Could you confirm if OptScale supports mongodb+srv? If so, what would be the correct way to configure it?

Thanks in advance!

**Comment by cupello** [comment, marked as answer]
I was able to figure it out through the code. It turns out that you just need to add the MongoDB URI (either mongodb or mongodb+srv) in the url field inside the YAML file:

optscale/optscale-deploy/optscale/values.yaml

```
mongo:
  external: false
  name: &mongo_name mongo
  replicaCount: 1
  cache_size: 1.0
  url: mongodb+srv://optscale_api:<db_password>@asdasd.asdasd.mongodb.net/?retryWrites=true&w=majority&appName=optscale
```

(Just leaving this here in case someone else needs it.)
