### ISSUE TITLE
Login issue: Google oauth and Microsoft oauth not working properly.

### ISSUE THREAD

**Issue by kiranRadhh** [hystax/optscale#141]
Hi @maxb-hystax , @nk-hystax ,

Could you please help us in resolving this issue !

**Describe the bug**
While trying to login using google / microsoft, getting errors. Please advice !

**To Reproduce**
1. Edit the overlay file with the google / microsoft oauth values as desired.
2. Complete the deployment steps for deploying the application
3. Open the login page of the application
4. Click on login with google / microsoft.
5. See error

**Expected behavior**
Able to login using google / microsoft login options.

**Screenshots**
This is a screenshot of the error page getting while trying to use google oauth for login. 
![Screenshot 2023-09-28 190218](https://github.com/hystax/optscale/assets/139243190/4bf5653d-d13e-4579-a1c2-985b45309a94)

We created microsoft oauth app registraion and passed the client id in the overlay. but the home page of the application itself is not loading. This is the ss of the home page error message while using microsoft oauth.
![Screenshot 2023-09-14 182408](https://github.com/hystax/optscale/assets/139243190/bc073ef5-44ed-4ac8-b8ec-326aaadd24a6)

**Additional context**
What should the redirect URL set to in the google oauth settings ?

Thanks!

**Comment by nexusriot** [comment]
did you add to the user_template.yml valid credentials?

```
# This overlay should be used for all non-production environments (?)
# - https://console.developers.google.com/ to see registered origins for the Google OAuth client"
# - https://portal.azure.com/ to see registered origins for the Microsoft OAuth client"
auth:
  google_oauth_client_id: ""
  microsoft_oauth_client_id: ""
```

**Comment by kiranRadhh** [comment]
Yes, when we add the oauth for google client the application is loading but while trying to login with google, getting the error (first screenshot)
What should the redirect URL set to in the google oauth settings ?

when I set the microsoft oauth client id alone it doesnt load the application, getting something went wrong! error page (second screenshot)

**Comment by kiranRadhh** [comment]
Yes, when we add the oauth for google client the application is loading but while trying to login with google, getting the error (first screenshot)
What should the redirect URL set to in the google oauth settings ?

when I set the microsoft oauth client id alone it doesnt load the application, getting something went wrong! error page (second screenshot)

**Comment by tguisep** [comment]
Hello,
Update your base code to integrate last fix.
https://github.com/hystax/optscale/pull/97

Regarding google configuration:
**Authorized JavaScript origins:**
https://optscale.your.url

**Authorized redirect URIs**
https://optscale..your.url/login

You also need to build your own image of ngui with the good values:
https://github.com/hystax/optscale/blob/integration/ngui/ui/.env.sample

And deploy it in place of the hystax image build.

**Comment by artm-hx** [comment]
Hi,
https://github.com/hystax/optscale/pull/97 changes are required to make it working.

Also user_template.yml should have filled the following:
```
# - https://console.developers.google.com/ to see registered origins for the Google OAuth client"
# - https://portal.azure.com/ to see registered origins for the Microsoft OAuth client"
auth:
  google_oauth_client_id: 
  google_oauth_client_secret: 
  microsoft_oauth_client_id: 

ngui:
  env:
    google_oauth_client_id: 
    microsoft_oauth_client_id: 
```

Additional notes:
- registered Google OAuth client requires valid **Authorized JavaScript origins** value. For example https://your-optscale.com
![image](https://github.com/hystax/optscale/assets/111763359/a2f98d9d-dcd9-4644-aad0-48559b748683)

- registered Microsoft application requires 2 valid **Redirect URIs** values on application **Authentication** page.  For example https://your-optscale.com/login and https://your-optscale.com/register
![image](https://github.com/hystax/optscale/assets/111763359/4702ac9c-1030-4fb1-848e-14764cfdae81)


Also https://github.com/hystax/optscale/blob/integration/ngui/ui/.env.sample is just example. These values are controlled by user_template.yml content - https://github.com/hystax/optscale/blob/integration/optscale-deploy/optscale/templates/ngui.yaml#L58
