### ISSUE TITLE
Overlay Setup for AWS

### ISSUE THREAD

**Issue by laurie-kepford** [hystax/optscale#32]
The instruction say to modify overlay/user_template.yml

I want to set this up for AWS only.
What AWS permissions does optscale need?
What would go in here?
```
    pricing_data:
      dataset_name: pricing_dataset
      table_name: cloud_pricing_export
    project_id: yourprojectid
```
How much, if any of these items can be configured after the install?
