### ISSUE TITLE
Where to add admin email id . When new user registers for live demo where i can recieve email on that admin email.

### ISSUE THREAD

**Issue by trendsetterfinops** [hystax/optscale#569]

**Comment by stanfra** [comment]
Hi @trendsetterfinops, you need to add next parameters into your user_template.yml file:
```
optscale_service_emails:
  recipient: "<admin_email>"
  enabled: true

optscale_error_emails:
  recipient: "<admin_email>"
  enabled: true
```

And after that execute command to apply changes(you use this command to start cluster):
`./runkube.py --with-elk  -o overlay/user_template.yml -- <deployment name> <version>`
