### ISSUE TITLE
Add documentation for configuring external MongoDB in OptScale

### ISSUE THREAD

**Issue by cupello** [hystax/optscale#602]
Currently, there is no official documentation on how to configure OptScale with an external MongoDB instance. Clear guidelines would help users who want to use their own database instead of the default setup.

Proposed solution:
Provide step-by-step instructions on how to configure an external MongoDB instance for OptScale.
Include details on connection settings, authentication, and any necessary environment variables.

Would love to see this added to the documentation! Let me know if I can provide any additional details.

**Comment by stanfra** [comment]
Hi @cupello, our team has taken your request into work, as soon as the guide is ready, we will write in this issue.

**Comment by cupello** [comment]
Thank you @stanfra for the quick response!

I was able to figure it out through the code. It turns out that you just need to add the MongoDB URI (either mongodb or mongodb+srv) in the url field inside the YAML file:

optscale/optscale-deploy/optscale/values.yaml

```
mongo:
  external: false
  name: &mongo_name mongo
  replicaCount: 1
  cache_size: 1.0
  url: mongodb+srv://optscale_api:<db_password>@asdasd.asdasd.mongodb.net/?retryWrites=true&w=majority&appName=optscale
```
(Just leaving this here in case someone else needs it.)

However, I believe there might be a missing configuration, as when deploying a fresh installation with a clean database, I’m getting the following error:

```
Failed to apply version 202111031530000
clickhouse_driver.errors.ServerException: Code: 57.
DB::Exception: Table default.expenses already exists. Stack trace:
```

I checked, and the collection does exist—it was created by one of the migrations—but even after cleaning the database and running it again, the error still occurs. Do you know what might be causing this?
